"""Ports: the persistence interfaces the backend's services depend on."""
from backend.application.ports.repositories import (
    AssetExtractionRepository,
    ConversationRepository,
    CorpusDigestRepository,
    DigestRecord,
    DocumentAssetRepository,
    DocumentPairRecord,
    DocumentPairRepository,
    EntityAttributeRecord,
    EntityAttributeRepository,
    IngestJobRecord,
    IngestJobRepository,
    JobStep,
    MessageHead,
    NewMessage,
    ParentChunkRecord,
    ParentChunkRepository,
    SectionSummaryRepository,
    SessionSummary,
    StoredAssetRef,
    StoredExtraction,
    StoredMessage,
    StoredSession,
)
from backend.application.ports.unit_of_work import UnitOfWork, UnitOfWorkFactory

__all__ = [
    "AssetExtractionRepository",
    "ConversationRepository",
    "CorpusDigestRepository",
    "DigestRecord",
    "DocumentAssetRepository",
    "DocumentPairRecord",
    "DocumentPairRepository",
    "EntityAttributeRecord",
    "EntityAttributeRepository",
    "IngestJobRecord",
    "IngestJobRepository",
    "JobStep",
    "MessageHead",
    "NewMessage",
    "ParentChunkRecord",
    "ParentChunkRepository",
    "SectionSummaryRepository",
    "SessionSummary",
    "StoredAssetRef",
    "StoredExtraction",
    "StoredMessage",
    "StoredSession",
    "UnitOfWork",
    "UnitOfWorkFactory",
]
