services:
  backend:
    image: ${REGISTRY_IMAGE_PREFIX:?required}/backend:${BACKEND_IMAGE_TAG:?required}
    pull_policy: always
  frontend:
    image: ${REGISTRY_IMAGE_PREFIX:?required}/frontend:${FRONTEND_IMAGE_TAG:?required}
    pull_policy: always
  identity:
    image: ${REGISTRY_IMAGE_PREFIX:?required}/identity:${IDENTITY_IMAGE_TAG:?required}
    pull_policy: always
  records:
    image: ${REGISTRY_IMAGE_PREFIX:?required}/records:${RECORDS_IMAGE_TAG:?required}
    pull_policy: always
  sis:
    image: ${REGISTRY_IMAGE_PREFIX:?required}/sis:${SIS_IMAGE_TAG:?required}
    pull_policy: always
