#!/usr/bin/env python3
"""Render non-secret environment profiles, Nginx routes and the access directory."""

from __future__ import annotations

import argparse
import csv
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PORTS = {
    "POSTGRES": 5432,
    "REDIS": 6379,
    "ETCD": 2379,
    "MINIO_API": 9000,
    "MINIO_CONSOLE": 9001,
    "MILVUS": 19530,
    "MILVUS_HEALTH": 9091,
    "ATTU": 8081,
    "SIS": 8300,
    "IDENTITY": 8200,
    "RECORDS": 8100,
    "BACKEND": 8000,
    "FRONTEND": 3000,
}
SERVICES = {
    "superagent": ("FRONTEND", "/", False),
    "sis": ("SIS", "/ui/", False),
    "api": ("BACKEND", "/docs", False),
    "auth": ("IDENTITY", "/docs", False),
    "records": ("RECORDS", "/docs", False),
    "attu": ("ATTU", "/", True),
    # MinIO has native login/S3 signatures; proxy Basic Auth would replace Authorization.
    "minio": ("MINIO_CONSOLE", "/", False),
    "s3": ("MINIO_API", "/minio/health/live", False),
    "milvus": ("MILVUS_HEALTH", "/healthz", True),
    "etcd": ("ETCD", "/health", True),
}


def render_vhost(domain: str, port: int, service: str, protected: bool, production: bool) -> str:
    access = (
        (
            '    auth_basic "Aurexis environment administration";\n'
            "    auth_basic_user_file /etc/nginx/aurexis-access/ENVIRONMENT.htpasswd;\n"
        )
        if protected
        else ""
    )
    locations = ""
    if production:
        locations += "    location ~ ^/(docs|redoc|openapi\\.json)(/|$) { return 404; }\n"
    if service == "superagent":
        # This host used to route /v1 to SIS. Authentication now stays on the UI origin.
        locations += (
            "    location = /.well-known/jwks.json { proxy_pass http://127.0.0.1:IDENTITY_PORT; }\n"
        )
    if service == "sis":
        locations += "    location = / { return 302 /ui/; }\n"
    if service == "milvus":
        locations += """    location ~ ^/v[12]/ {
        proxy_pass http://127.0.0.1:MILVUS_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
"""
    return f"""# Generated by deploy/scripts/render-environments.py. Edit deploy/environments.json.
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};
    location ^~ /.well-known/acme-challenge/ {{ root /var/www/certbot; }}
    location / {{ return 301 https://$host$request_uri; }}
}}
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain};
    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 512m;
    client_body_timeout 300s;
{access}    location ^~ /.well-known/acme-challenge/ {{
        auth_basic off;
        root /var/www/certbot;
    }}
{locations}    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $aurexis_connection_upgrade;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_connect_timeout 15s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
    }}
}}
"""


def artifacts() -> dict[Path, str]:
    configs = json.loads((ROOT / "deploy/environments.json").read_text(encoding="utf-8"))
    result: dict[Path, str] = {}
    docs = [
        "# Environment access directory",
        "",
        "These are configured addresses, not confirmation that DNS or deployment is live.",
        "",
        "The original CI, changed-service CD and release-record stages are preserved.",
        "A main release promotes dev -> test -> production, with approval at each environment.",
        "After dev succeeds, the tester may approve test to pull the SAME frozen images; production follows only after successful test and its own approval.",
        "",
        "Environment data, keys, networks, container names and ports are isolated.",
        "Management endpoints require the environment-specific Nginx password.",
        "",
    ]
    dns = io.StringIO()
    writer = csv.writer(dns, lineterminator="\n")
    writer.writerow(["environment", "type", "host", "value", "ttl"])
    all_domains: set[str] = set()
    all_ports: set[int] = set()
    for environment, config in configs.items():
        production = environment == "production"
        ports = {key: value + config["port_offset"] for key, value in PORTS.items()}
        assert not (all_ports & set(ports.values())), "Environment host ports overlap"
        all_ports.update(ports.values())
        domains = config["domains"]
        assert set(domains) == ({"superagent", "sis"} if production else set(SERVICES))
        assert not (all_domains & set(domains.values())), "Environment domains overlap"
        all_domains.update(domains.values())
        stack = "superagent" if production else f"superagent-{environment}"
        values = {
            "DEPLOY_ENVIRONMENT": environment,
            "STACK_NAME": stack,
            "PUBLIC_DOMAINS": " ".join(domains.values()),
            "SUPERAGENT_DOMAIN": domains["superagent"],
            "SIS_DOMAIN": domains["sis"],
            "RETIRED_DOMAINS": "auth.aurexis.cc api.aurexis.cc" if production else "",
            "CORS_ALLOW_ORIGINS": ",".join("https://" + domain for domain in domains.values()),
            "SIS_CORS_ORIGINS": "https://" + domains["sis"],
            # Reuse the same frontend image in every environment; /v1 proxies to identity.
            "VITE_IDENTITY_BASE_URL": "",
            "VITE_API_BASE_URL": "",
            "MINIO_BROWSER_REDIRECT_URL": "" if production else "https://" + domains["minio"],
        }
        values.update({key + "_HOST_PORT": str(port) for key, port in ports.items()})
        local_checks = [
            f"http://127.0.0.1:{ports[key]}/health"
            for key in ("BACKEND", "IDENTITY", "RECORDS", "SIS")
        ]
        local_checks += [f"http://127.0.0.1:{ports['FRONTEND']}/"]
        values["LOCAL_CHECK_URLS"] = " ".join(local_checks)
        public_checks: list[str] = []
        protected_checks: list[str] = []
        docs += [f"## {environment}", "", "| Service | Address | Access |", "| --- | --- | --- |"]
        for service, domain in domains.items():
            assert len(domain.split(".")[0]) <= 63
            port_key, path, protected = SERVICES[service]
            url = f"https://{domain}{path}"
            docs.append(
                f"| {service} | [{url}]({url}) | {'Management login' if protected else 'Application login / API credentials'} |"
            )
            writer.writerow(
                [
                    environment,
                    "A",
                    domain.removesuffix(".aurexis.cc"),
                    config["public_ip"],
                    "Automatic",
                ]
            )
            nginx = render_vhost(domain, ports[port_key], service, protected, production)
            nginx = nginx.replace("ENVIRONMENT.htpasswd", f"{environment}.htpasswd")
            nginx = nginx.replace("IDENTITY_PORT", str(ports["IDENTITY"]))
            nginx = nginx.replace("MILVUS_PORT", str(ports["MILVUS"]))
            result[ROOT / f"deploy/nginx/{environment}/{domain}.conf"] = nginx
            check = (
                f"https://{domain}{('/health' if service in ('api', 'auth', 'records') else path)}"
            )
            (protected_checks if protected else public_checks).append(check)
        values["PUBLIC_CHECK_URLS"] = " ".join(public_checks)
        values["PROTECTED_CHECK_URLS"] = " ".join(protected_checks)
        result[ROOT / f"deploy/environments/{environment}.env"] = (
            "# Generated. Non-secret topology; credentials belong in the server .env.\n"
            + "".join(f"{key}='{value}'\n" for key, value in values.items())
        )
        if not production:
            docs += [
                "",
                "TCP services use SSH tunnels; their host ports bind to loopback only.",
                "",
                "| Service | Server port | Local tunnel address |",
                "| --- | --- | --- |",
            ]
            for service in ("POSTGRES", "REDIS", "MILVUS"):
                port = ports[service]
                docs.append(f"| {service} | {port} | `127.0.0.1:{port}` |")
            forwards = " ".join(
                f"-L {ports[key]}:127.0.0.1:{ports[key]}" for key in ("POSTGRES", "REDIS", "MILVUS")
            )
            docs += [
                "",
                "```sh",
                f"ssh -N {forwards} root@{config['public_ip']}",
                "```",
                "Use that environment's database credentials. PostgreSQL, Redis and Milvus TCP are not web pages.",
                "",
            ]
        else:
            docs += [
                "",
                "Only these two application hosts are published. Swagger routes return 404.",
                "Authentication remains available at the SuperAgent origin under /v1/.",
                "Old api/auth hosts return 404 after migration; remove their DNS A/AAAA records after verification.",
                "",
            ]
    result[ROOT / "deploy/ENVIRONMENT_LINKS.md"] = "\n".join(docs).rstrip() + "\n"
    result[ROOT / "deploy/dns-records.csv"] = dns.getvalue()
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated file is out of date: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
