"""add guardians

Three tables, so that a child's parents are a fact this service holds rather than one it
refers elsewhere for.

`guardian_phones` is separate from `guardians` on purpose: one parent legitimately has two
numbers, and a phone column would either lose the second or duplicate the person. Its
unique constraint on `phone` is the load-bearing one — it makes "this number belongs to
exactly one adult" something the database enforces, which is what both the importer's
deduplication and any future parent login by verification code depend on.

`student_guardians.can_view_records` defaults to false here while the importer sets it
true. That asymmetry is deliberate: the default protects any code path that never
considered the question, and the importer is a registrar who has.

Purely additive. No existing table is touched, so the downgrade is a genuine inverse and
loses only what this revision created.

Revision ID: 0002
Revises: f27c8792d023
Created: 2026-08-16 12:28:48.032220

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = 'f27c8792d023'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('full_name_ar', sa.String(length=255), nullable=False),
    sa.Column('full_name_en', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(full_name_ar)) > 0 OR length(trim(full_name_en)) > 0', name=op.f('ck_guardians_ck_guardians_has_name')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians')),
    sa.UniqueConstraint('public_id', name=op.f('uq_guardians_public_id'))
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index('ix_guardians_name_ar', ['full_name_ar'], unique=False)
        batch_op.create_index('ix_guardians_name_en', ['full_name_en'], unique=False)

    op.create_table('guardian_phones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_guardian_phones_guardian_id_guardians'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardian_phones')),
    sa.UniqueConstraint('phone', name=op.f('uq_guardian_phones_phone'))
    )
    with op.batch_alter_table('guardian_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardian_phones_guardian_id'), ['guardian_id'], unique=False)
        batch_op.create_index('uq_guardian_phones_primary', ['guardian_id'], unique=True, sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary'))

    op.create_table('student_guardians',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=16), nullable=False),
    sa.Column('relationship_label', sa.Text(), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('can_view_records', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('restriction_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_student_guardians_guardian_id_guardians'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_guardians_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_guardians')),
    sa.UniqueConstraint('student_id', 'guardian_id', name='uq_student_guardian_link')
    )
    with op.batch_alter_table('student_guardians', schema=None) as batch_op:
        batch_op.create_index('ix_student_guardians_lookup', ['guardian_id', 'can_view_records'], unique=False)
        batch_op.create_index('ix_student_guardians_student', ['student_id'], unique=False)
        batch_op.create_index('uq_student_guardians_primary_contact', ['student_id'], unique=True, sqlite_where=sa.text('is_primary_contact = 1'), postgresql_where=sa.text('is_primary_contact'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # A downgrade that raises is a migration that can only go forwards, and the moment
    # it matters is a failed 02:00 deploy with a half-applied schema. Write the real
    # inverse here, even when it is a data-losing one -- say so in a comment instead.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_guardians', schema=None) as batch_op:
        batch_op.drop_index('uq_student_guardians_primary_contact', sqlite_where=sa.text('is_primary_contact = 1'), postgresql_where=sa.text('is_primary_contact'))
        batch_op.drop_index('ix_student_guardians_student')
        batch_op.drop_index('ix_student_guardians_lookup')

    op.drop_table('student_guardians')
    with op.batch_alter_table('guardian_phones', schema=None) as batch_op:
        batch_op.drop_index('uq_guardian_phones_primary', sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary'))
        batch_op.drop_index(batch_op.f('ix_guardian_phones_guardian_id'))

    op.drop_table('guardian_phones')
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index('ix_guardians_name_en')
        batch_op.drop_index('ix_guardians_name_ar')

    op.drop_table('guardians')
    # ### end Alembic commands ###
