import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import './assets/styles/main.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

const app = createApp(App);
const pinia = createPinia();

app.use(pinia);
app.mount('#app');
import './assets/styles/aurexis-final-match-v5.css';
import './assets/styles/aurexis-theme-lights-auth-v6.css';
import './assets/styles/aurexis-fullscreen-v7.css';
import './assets/styles/aurexis-auth-repair-v8.css';

import './assets/styles/aurexis-app-mobile-v10-7.css';
import './assets/styles/aurexis-mobile-chat-v10-8.css';
import './assets/styles/aurexis-sidebar-composer-v10-9.css';
import './assets/styles/aurexis-mobile-sidebar-icon-v10-9-1.css';
import './assets/styles/aurexis-desktop-sidebar-toggle-v10-9-2.css';
import './assets/styles/aurexis-sidebar-toggle-exact-v10-9-3.css';
import './assets/styles/aurexis-mobile-sidebar-footer-v10-9-4.css';
import './assets/styles/aurexis-mobile-sidebar-bottom-exact-v10-9-5.css';
import './assets/styles/aurexis-mobile-sidebar-cleanup-v10-9-6.css';
import './assets/styles/aurexis-history-v11-0.css';
import './assets/styles/aurexis-knowledge-v11-1.css';
import './assets/styles/aurexis-knowledge-mobile-polish-v11-1-1.css';
import './assets/styles/aurexis-chat-composer-clean-v11-2.css';
import './assets/styles/aurexis-mobile-chat-precision-v11-3.css';
import './assets/styles/aurexis-theme-coherence-v11-4.css';
import './assets/styles/aurexis-circular-menu-icon-v11-5.css';
import './assets/styles/aurexis-menu-icon-precision-v11-5-1.css';
import './assets/styles/aurexis-desktop-tablet-final-sync-v11-6.css';
import './assets/styles/aurexis-desktop-icon-rail-v11-7.css';
import './assets/styles/aurexis-collapsed-rail-refined-v11-9.css';
import './assets/styles/aurexis-collapsed-rail-final-v11-10.css';
import './assets/styles/aurexis-collapsed-rail-history-v11-10-1.css';
import './assets/styles/aurexis-welcome-composer-v11-11.css';
import './assets/styles/aurexis-responsive-welcome-copy-v11-11-1.css';