"""initial schema

Revision ID: f27c8792d023
Revises: 
Created: 2026-08-14 14:20:09.594880

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f27c8792d023'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('code', name=op.f('uq_academic_years_code'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_api_keys_prefix'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('ix_api_keys_prefix_active', ['prefix', 'is_active'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('batch_id', name=op.f('uq_import_batches_batch_id'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index('ix_import_batches_actor_time', ['actor', 'created_at'], unique=False)
        batch_op.create_index('ix_import_batches_status_expiry', ['status', 'expires_at'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_number', sa.String(length=64), nullable=False),
    sa.Column('full_name_ar', sa.String(length=255), nullable=False),
    sa.Column('full_name_en', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('student_number', name=op.f('uq_students_student_number'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('ix_students_name_ar', ['full_name_ar'], unique=False)
        batch_op.create_index('ix_students_name_en', ['full_name_en'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code'))
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index('ix_subjects_order', ['display_order'], unique=False)

    op.create_table('year_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_year_levels')),
    sa.UniqueConstraint('code', name=op.f('uq_year_levels_code'))
    )
    with op.batch_alter_table('year_levels', schema=None) as batch_op:
        batch_op.create_index('ix_year_levels_order', ['display_order'], unique=False)

    op.create_table('class_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('year_level_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_class_sections_academic_year_id_academic_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_level_id'], ['year_levels.id'], name=op.f('fk_class_sections_year_level_id_year_levels'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_sections')),
    sa.UniqueConstraint('academic_year_id', 'year_level_id', 'code', name='uq_class_section_year_level_code')
    )
    with op.batch_alter_table('class_sections', schema=None) as batch_op:
        batch_op.create_index('ix_class_sections_year_code', ['academic_year_id', 'code'], unique=False)
        batch_op.create_index('ix_class_sections_year_level', ['academic_year_id', 'year_level_id'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    sa.UniqueConstraint('batch_id', 'line_number', name='uq_import_row_line')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index('ix_import_rows_batch_outcome', ['batch_id', 'outcome', 'line_number'], unique=False)

    op.create_table('terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ends_on >= starts_on', name=op.f('ck_terms_ck_terms_dates_ordered')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_terms_academic_year_id_academic_years'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms')),
    sa.UniqueConstraint('code', name=op.f('uq_terms_code'))
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index('ix_terms_window', ['starts_on', 'ends_on'], unique=False)
        batch_op.create_index('ix_terms_year_sequence', ['academic_year_id', 'sequence'], unique=False)

    op.create_table('class_enrolments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ends_on IS NULL OR ends_on >= starts_on', name=op.f('ck_class_enrolments_ck_class_enrolments_dates_ordered')),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], name=op.f('fk_class_enrolments_class_section_id_class_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_class_enrolments_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_enrolments')),
    sa.UniqueConstraint('student_id', 'class_section_id', 'starts_on', name='uq_class_enrolment_placement')
    )
    with op.batch_alter_table('class_enrolments', schema=None) as batch_op:
        batch_op.create_index('ix_class_enrolments_section_window', ['class_section_id', 'starts_on', 'ends_on'], unique=False)
        batch_op.create_index('ix_class_enrolments_student_on_date', ['student_id', 'starts_on', 'ends_on'], unique=False)
        batch_op.create_index('uq_class_enrolments_open_per_student', ['student_id'], unique=True, sqlite_where=sa.text('ends_on IS NULL'), postgresql_where=sa.text('ends_on IS NULL'))

    op.create_table('subject_grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name=op.f('ck_subject_grades_ck_subject_grades_percentage_range')),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], name=op.f('fk_subject_grades_class_section_id_class_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_subject_grades_student_id_students'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_grades_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_subject_grades_term_id_terms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_grades')),
    sa.UniqueConstraint('student_id', 'subject_id', 'term_id', name='uq_subject_grade_identity')
    )
    with op.batch_alter_table('subject_grades', schema=None) as batch_op:
        batch_op.create_index('ix_subject_grades_sheet', ['term_id', 'class_section_id', 'subject_id'], unique=False)
        batch_op.create_index('ix_subject_grades_student_term', ['student_id', 'term_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # A downgrade that raises is a migration that can only go forwards, and the moment
    # it matters is a failed 02:00 deploy with a half-applied schema. Write the real
    # inverse here, even when it is a data-losing one -- say so in a comment instead.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_grades', schema=None) as batch_op:
        batch_op.drop_index('ix_subject_grades_student_term')
        batch_op.drop_index('ix_subject_grades_sheet')

    op.drop_table('subject_grades')
    with op.batch_alter_table('class_enrolments', schema=None) as batch_op:
        batch_op.drop_index('uq_class_enrolments_open_per_student', sqlite_where=sa.text('ends_on IS NULL'), postgresql_where=sa.text('ends_on IS NULL'))
        batch_op.drop_index('ix_class_enrolments_student_on_date')
        batch_op.drop_index('ix_class_enrolments_section_window')

    op.drop_table('class_enrolments')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index('ix_terms_year_sequence')
        batch_op.drop_index('ix_terms_window')

    op.drop_table('terms')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index('ix_import_rows_batch_outcome')

    op.drop_table('import_rows')
    with op.batch_alter_table('class_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_class_sections_year_level')
        batch_op.drop_index('ix_class_sections_year_code')

    op.drop_table('class_sections')
    with op.batch_alter_table('year_levels', schema=None) as batch_op:
        batch_op.drop_index('ix_year_levels_order')

    op.drop_table('year_levels')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index('ix_subjects_order')

    op.drop_table('subjects')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('ix_students_name_en')
        batch_op.drop_index('ix_students_name_ar')

    op.drop_table('students')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_status_expiry')
        batch_op.drop_index('ix_import_batches_actor_time')

    op.drop_table('import_batches')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_keys_prefix_active')

    op.drop_table('api_keys')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
